Algoritmo "Leitura de valor"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Exercicio J
// Autor(a)    : Stephany Camily dos
Var
   valor: Inteiro

Inicio
   Escreva("Digite um valor entre 1 e 9: ")
   Leia(valor)

   Se valor >= 1 E valor <= 9 Então
      Escreva("O valor está na faixa permitida.")
   Senão
      Escreva("O valor está fora da faixa permitida.")
   FimSe

Fimalgoritmo