Algoritmo "Menor que três"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Exercicio K
// Autor(a)    : Stephany Camily dos
Var

 valor: inteiro

Inicio
   Escreva("Digite um valor inteiro: ")
   Leia(valor)

   Se valor <= 3 Então
      Escreva("O valor digitado é: ", valor)
   Senão
      Escreva("O valor digitado não é maior que três.")
   FimSe

Fimalgoritmo