Algoritmo "Sr ou Sra"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Exercicio L
// Autor(a)    : Stephany Camily dos
Var
   nome: caractere
   sexo: caractere

Inicio
   Escreva("Digite seu nome: ")
   Leia(nome)
   Escreva("Digite seu sexo (M/F): ")
   Leia(sexo)

   Se sexo = "M" entao
      Escreva("llmo Sr. ", nome)
   Senao
      Escreva("llma Sra.: ", nome)
   FimSe

Fimalgoritmo