Algoritmo "Converter F para C"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   :Converter Fahrenheit para Celsius- Exercicio 7b
// Autor(a)    : Stephany Camily dos Santos

Var
grausF, grausC: Real


Inicio
   Escreva("Digite a temperatura em graus Fahrenheit: ")
   Leia(grausF)

   grausC <- (grausF - 32) * (5 / 9)

   Escreva("A temperatura em graus Celsius é: ", grausC)

Fimalgoritmo