Algoritmo "Conversor de C para F"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   :Conversor de Celsius para Fahrenheit- Exercicio 7a
// Autor(a)    : Stephany Camily dos Santos

Var

   grausC, grausF: Real

Inicio
   Escreva("Digite a temperatura em graus Celsius: ")
   Leia(grausC)

   grausF <- (9 * C + 160) / 5

   Escreva("A temperatura em graus Fahrenheit é: ", grausF)


Fimalgoritmo